---
- hosts: all:!UCI-Nodes
  become: True
  roles:
    - role: debops.apt_preferences
    - role: debops.apt
    - common
    - wireguard
- hosts: WebServers
  become: True
  roles:
    - nginx
    - firmware-index
- hosts:
  - Concentrators
  - WebServers
  - Exits
  become: True
  roles:
    - vrf
    - bird
    - python-venv
    - wireguard-backbone
- hosts: etcd_cluster
  become: True
  roles:
    - etcd
- hosts: etcd_clients
  become: True
  roles:
    - etcd-client
- hosts: Concentrators
  become: True
  roles:
    - wireguard-concentrator
- hosts:
  - client
  - concentrator1
  - node1
  become: True
  roles:
  -  python-dev
- hosts:
  - exit1
  become: True
  roles:
    - wireguard-exit
    - bind
- hosts: Nodes:!UCI-Nodes
  become: True
  roles:
    - vrf
    - python-venv
    - node
    - wireguard-node
    - bridge
    - batman
- hosts: UCI-Nodes
  become: True
  roles:
    - vrf-uci
    - wireguard
    - wireguard-node-uci
