---
- name: Install concentrator services
  copy:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'concentrator-route.service', dest: '/etc/systemd/system/', mode: 644 }
    - { src: 'concentrator-config.service', dest: '/etc/systemd/system/', mode: 644 }

- name: Install etcd-config-web.service
  template:
    src: etcd-config-web.service.j2
    dest: /etc/systemd/system/etcd-config-web.service
    mode: 0644
  notify:
    - Restart etcd-config-web

- name: Copy nodeconfig certificates
  copy:
    src:  "{{ item }}"
    dest: "/etc/ffbs/"
    mode: 0644
  with_items:
    - 'node-config.sec'
    - 'node-config.pub'

- name: Enable and start systemd service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - etcd-config-web.service
    - concentrator-route.service
    - concentrator-config.service

- name: Install nginx concentrator config
  template:
    src: nginx-location.conf.j2
    dest: /etc/nginx/site-default.d/50-concentrator.conf
    mode: 0644
  notify:
    - Reload nginx
